export const USERNAME_IS_EMPTY = 'USERNAME_IS_EMPTY';
export const PASSWORD_IS_EMPTY = 'PASSWORD_IS_EMPTY';
export const PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 =
  'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8';
export const WRONG_PASSWORD = 'WRONG_PASSWORD';
export const SOME_THING_WENT_WRONG = 'SOME_THING_WENT_WRONG';
export const USER_EXISTS_ALREADY = 'USER_EXISTS_ALREADY';
export const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';
export const TOKEN_IS_EMPTY = 'TOKEN_IS_EMPTY';
export const EMPTY_ROLE = 'EMPTY_ROLE';
export const EMPTY_FULLNAME = 'EMPTY_FULLNAME';
export const EVENT_TYPE_IS_EMPTY = 'EVENT_TYPE_IS_EMPTY';
export const LOCATION_IS_EMPTY = 'LOCATION_IS_EMPTY';
export const ACTION_NOT_ACCEPTABLE = 'ACTION_NOT_ACCEPTABLE';
export const EMPTY_DATE = 'EMPTY_DATE';
export const EMPTY_REJECTION_RESULT = 'EMPTY_REJECTION_RESULT';
export const ADMIN = 'ADMIN';
export const COMPANY = 'COMPANY';
export const STATUS = {
  PENDING_REVIEW: 'pending_review',
  APPROVED: 'approved',
  REJECTED: 'rejected'
};
